/*
FunLess Platfom API

Testing ModulesApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_openapi_ModulesApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test ModulesApiService CreateModule", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.ModulesApi.CreateModule(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test ModulesApiService DeleteModule", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var moduleName string

        resp, httpRes, err := apiClient.ModulesApi.DeleteModule(context.Background(), moduleName).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test ModulesApiService ListModules", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.ModulesApi.ListModules(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test ModulesApiService ShowModuleByName", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var moduleName string

        resp, httpRes, err := apiClient.ModulesApi.ShowModuleByName(context.Background(), moduleName).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test ModulesApiService UpdateModule", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var moduleName string

        resp, httpRes, err := apiClient.ModulesApi.UpdateModule(context.Background(), moduleName).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
