/*
FunLess Platfom API

The API for the FunLess Platform

API version: 0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FunctionCreateUpdateSinksInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FunctionCreateUpdateSinksInner{}

// FunctionCreateUpdateSinksInner struct for FunctionCreateUpdateSinksInner
type FunctionCreateUpdateSinksInner struct {
	// Type of the data sink
	Type *string `json:"type,omitempty"`
	// Additional parameters for the data sink (usually connection params)
	Params map[string]interface{} `json:"params,omitempty"`
}

// NewFunctionCreateUpdateSinksInner instantiates a new FunctionCreateUpdateSinksInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunctionCreateUpdateSinksInner() *FunctionCreateUpdateSinksInner {
	this := FunctionCreateUpdateSinksInner{}
	return &this
}

// NewFunctionCreateUpdateSinksInnerWithDefaults instantiates a new FunctionCreateUpdateSinksInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunctionCreateUpdateSinksInnerWithDefaults() *FunctionCreateUpdateSinksInner {
	this := FunctionCreateUpdateSinksInner{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *FunctionCreateUpdateSinksInner) GetType() string {
	if o == nil || isNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionCreateUpdateSinksInner) GetTypeOk() (*string, bool) {
	if o == nil || isNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *FunctionCreateUpdateSinksInner) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *FunctionCreateUpdateSinksInner) SetType(v string) {
	o.Type = &v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *FunctionCreateUpdateSinksInner) GetParams() map[string]interface{} {
	if o == nil || isNil(o.Params) {
		var ret map[string]interface{}
		return ret
	}
	return o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionCreateUpdateSinksInner) GetParamsOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.Params) {
		return map[string]interface{}{}, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *FunctionCreateUpdateSinksInner) HasParams() bool {
	if o != nil && !isNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given map[string]interface{} and assigns it to the Params field.
func (o *FunctionCreateUpdateSinksInner) SetParams(v map[string]interface{}) {
	o.Params = v
}

func (o FunctionCreateUpdateSinksInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FunctionCreateUpdateSinksInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !isNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	return toSerialize, nil
}

type NullableFunctionCreateUpdateSinksInner struct {
	value *FunctionCreateUpdateSinksInner
	isSet bool
}

func (v NullableFunctionCreateUpdateSinksInner) Get() *FunctionCreateUpdateSinksInner {
	return v.value
}

func (v *NullableFunctionCreateUpdateSinksInner) Set(val *FunctionCreateUpdateSinksInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctionCreateUpdateSinksInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctionCreateUpdateSinksInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctionCreateUpdateSinksInner(val *FunctionCreateUpdateSinksInner) *NullableFunctionCreateUpdateSinksInner {
	return &NullableFunctionCreateUpdateSinksInner{value: val, isSet: true}
}

func (v NullableFunctionCreateUpdateSinksInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctionCreateUpdateSinksInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


