/*
FunLess Platfom API

The API for the FunLess Platform

API version: 0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateFunction207ResponseDataEventsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFunction207ResponseDataEventsInner{}

// CreateFunction207ResponseDataEventsInner struct for CreateFunction207ResponseDataEventsInner
type CreateFunction207ResponseDataEventsInner struct {
	// Whether the corresponding event was connected successfully
	Status *string `json:"status,omitempty"`
	// Additional information on the error
	Message *string `json:"message,omitempty"`
}

// NewCreateFunction207ResponseDataEventsInner instantiates a new CreateFunction207ResponseDataEventsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFunction207ResponseDataEventsInner() *CreateFunction207ResponseDataEventsInner {
	this := CreateFunction207ResponseDataEventsInner{}
	return &this
}

// NewCreateFunction207ResponseDataEventsInnerWithDefaults instantiates a new CreateFunction207ResponseDataEventsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFunction207ResponseDataEventsInnerWithDefaults() *CreateFunction207ResponseDataEventsInner {
	this := CreateFunction207ResponseDataEventsInner{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateFunction207ResponseDataEventsInner) GetStatus() string {
	if o == nil || isNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFunction207ResponseDataEventsInner) GetStatusOk() (*string, bool) {
	if o == nil || isNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateFunction207ResponseDataEventsInner) HasStatus() bool {
	if o != nil && !isNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CreateFunction207ResponseDataEventsInner) SetStatus(v string) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateFunction207ResponseDataEventsInner) GetMessage() string {
	if o == nil || isNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFunction207ResponseDataEventsInner) GetMessageOk() (*string, bool) {
	if o == nil || isNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateFunction207ResponseDataEventsInner) HasMessage() bool {
	if o != nil && !isNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreateFunction207ResponseDataEventsInner) SetMessage(v string) {
	o.Message = &v
}

func (o CreateFunction207ResponseDataEventsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFunction207ResponseDataEventsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !isNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableCreateFunction207ResponseDataEventsInner struct {
	value *CreateFunction207ResponseDataEventsInner
	isSet bool
}

func (v NullableCreateFunction207ResponseDataEventsInner) Get() *CreateFunction207ResponseDataEventsInner {
	return v.value
}

func (v *NullableCreateFunction207ResponseDataEventsInner) Set(val *CreateFunction207ResponseDataEventsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFunction207ResponseDataEventsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFunction207ResponseDataEventsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFunction207ResponseDataEventsInner(val *CreateFunction207ResponseDataEventsInner) *NullableCreateFunction207ResponseDataEventsInner {
	return &NullableCreateFunction207ResponseDataEventsInner{value: val, isSet: true}
}

func (v NullableCreateFunction207ResponseDataEventsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFunction207ResponseDataEventsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


