/*
Funless Platfom API

The API for the Funless Platform

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// FunctionListError struct for FunctionListError
type FunctionListError struct {
	// The error message
	Error *string `json:"error,omitempty"`
}

// NewFunctionListError instantiates a new FunctionListError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunctionListError() *FunctionListError {
	this := FunctionListError{}
	return &this
}

// NewFunctionListErrorWithDefaults instantiates a new FunctionListError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunctionListErrorWithDefaults() *FunctionListError {
	this := FunctionListError{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *FunctionListError) GetError() string {
	if o == nil || isNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionListError) GetErrorOk() (*string, bool) {
	if o == nil || isNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *FunctionListError) HasError() bool {
	if o != nil && !isNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *FunctionListError) SetError(v string) {
	o.Error = &v
}

func (o FunctionListError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableFunctionListError struct {
	value *FunctionListError
	isSet bool
}

func (v NullableFunctionListError) Get() *FunctionListError {
	return v.value
}

func (v *NullableFunctionListError) Set(val *FunctionListError) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctionListError) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctionListError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctionListError(val *FunctionListError) *NullableFunctionListError {
	return &NullableFunctionListError{value: val, isSet: true}
}

func (v NullableFunctionListError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctionListError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


