/*
 * FunLess Platfom API
 *
 * The API for the FunLess Platform
 *
 * API version: 0.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2002 struct {
	Data *FnModuleNameBody `json:"data,omitempty"`
}
