/*
FunLess Platfom API

The API for the FunLess Platform

API version: 0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SubjectNameSubject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubjectNameSubject{}

// SubjectNameSubject struct for SubjectNameSubject
type SubjectNameSubject struct {
	Name *string `json:"name,omitempty"`
}

// NewSubjectNameSubject instantiates a new SubjectNameSubject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubjectNameSubject() *SubjectNameSubject {
	this := SubjectNameSubject{}
	return &this
}

// NewSubjectNameSubjectWithDefaults instantiates a new SubjectNameSubject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubjectNameSubjectWithDefaults() *SubjectNameSubject {
	this := SubjectNameSubject{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SubjectNameSubject) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubjectNameSubject) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SubjectNameSubject) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SubjectNameSubject) SetName(v string) {
	o.Name = &v
}

func (o SubjectNameSubject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubjectNameSubject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableSubjectNameSubject struct {
	value *SubjectNameSubject
	isSet bool
}

func (v NullableSubjectNameSubject) Get() *SubjectNameSubject {
	return v.value
}

func (v *NullableSubjectNameSubject) Set(val *SubjectNameSubject) {
	v.value = val
	v.isSet = true
}

func (v NullableSubjectNameSubject) IsSet() bool {
	return v.isSet
}

func (v *NullableSubjectNameSubject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubjectNameSubject(val *SubjectNameSubject) *NullableSubjectNameSubject {
	return &NullableSubjectNameSubject{value: val, isSet: true}
}

func (v NullableSubjectNameSubject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubjectNameSubject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


