/*
FunLess Platfom API

The API for the FunLess Platform

API version: 0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListModulesDefaultResponseErrors type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListModulesDefaultResponseErrors{}

// ListModulesDefaultResponseErrors struct for ListModulesDefaultResponseErrors
type ListModulesDefaultResponseErrors struct {
	Detail *string `json:"detail,omitempty"`
}

// NewListModulesDefaultResponseErrors instantiates a new ListModulesDefaultResponseErrors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListModulesDefaultResponseErrors() *ListModulesDefaultResponseErrors {
	this := ListModulesDefaultResponseErrors{}
	return &this
}

// NewListModulesDefaultResponseErrorsWithDefaults instantiates a new ListModulesDefaultResponseErrors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListModulesDefaultResponseErrorsWithDefaults() *ListModulesDefaultResponseErrors {
	this := ListModulesDefaultResponseErrors{}
	return &this
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *ListModulesDefaultResponseErrors) GetDetail() string {
	if o == nil || isNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListModulesDefaultResponseErrors) GetDetailOk() (*string, bool) {
	if o == nil || isNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *ListModulesDefaultResponseErrors) HasDetail() bool {
	if o != nil && !isNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *ListModulesDefaultResponseErrors) SetDetail(v string) {
	o.Detail = &v
}

func (o ListModulesDefaultResponseErrors) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListModulesDefaultResponseErrors) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	return toSerialize, nil
}

type NullableListModulesDefaultResponseErrors struct {
	value *ListModulesDefaultResponseErrors
	isSet bool
}

func (v NullableListModulesDefaultResponseErrors) Get() *ListModulesDefaultResponseErrors {
	return v.value
}

func (v *NullableListModulesDefaultResponseErrors) Set(val *ListModulesDefaultResponseErrors) {
	v.value = val
	v.isSet = true
}

func (v NullableListModulesDefaultResponseErrors) IsSet() bool {
	return v.isSet
}

func (v *NullableListModulesDefaultResponseErrors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListModulesDefaultResponseErrors(val *ListModulesDefaultResponseErrors) *NullableListModulesDefaultResponseErrors {
	return &NullableListModulesDefaultResponseErrors{value: val, isSet: true}
}

func (v NullableListModulesDefaultResponseErrors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListModulesDefaultResponseErrors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


