/*
FunLess Platfom API

The API for the FunLess Platform

API version: 0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ErrorErrors type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorErrors{}

// ErrorErrors struct for ErrorErrors
type ErrorErrors struct {
	Detail *string `json:"detail,omitempty"`
}

// NewErrorErrors instantiates a new ErrorErrors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorErrors() *ErrorErrors {
	this := ErrorErrors{}
	return &this
}

// NewErrorErrorsWithDefaults instantiates a new ErrorErrors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorErrorsWithDefaults() *ErrorErrors {
	this := ErrorErrors{}
	return &this
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *ErrorErrors) GetDetail() string {
	if o == nil || isNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorErrors) GetDetailOk() (*string, bool) {
	if o == nil || isNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *ErrorErrors) HasDetail() bool {
	if o != nil && !isNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *ErrorErrors) SetDetail(v string) {
	o.Detail = &v
}

func (o ErrorErrors) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorErrors) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	return toSerialize, nil
}

type NullableErrorErrors struct {
	value *ErrorErrors
	isSet bool
}

func (v NullableErrorErrors) Get() *ErrorErrors {
	return v.value
}

func (v *NullableErrorErrors) Set(val *ErrorErrors) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorErrors) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorErrors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorErrors(val *ErrorErrors) *NullableErrorErrors {
	return &NullableErrorErrors{value: val, isSet: true}
}

func (v NullableErrorErrors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorErrors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


