/*
 * Funless Platfom API
 *
 * The API for the Funless Platform
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The name of the function
type InlineResponse2001 struct {
	Result *interface{} `json:"result,omitempty"`
}
