/*
FunLess Platfom API

The API for the FunLess Platform

API version: 0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateFunction207ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFunction207ResponseData{}

// CreateFunction207ResponseData struct for CreateFunction207ResponseData
type CreateFunction207ResponseData struct {
	// The name of the function
	Name *string `json:"name,omitempty"`
	// The results of event connection, both successful and failed
	Events []CreateFunction207ResponseDataEventsInner `json:"events,omitempty"`
	Metadata *CreateFunction207ResponseDataMetadata `json:"metadata,omitempty"`
}

// NewCreateFunction207ResponseData instantiates a new CreateFunction207ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFunction207ResponseData() *CreateFunction207ResponseData {
	this := CreateFunction207ResponseData{}
	return &this
}

// NewCreateFunction207ResponseDataWithDefaults instantiates a new CreateFunction207ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFunction207ResponseDataWithDefaults() *CreateFunction207ResponseData {
	this := CreateFunction207ResponseData{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateFunction207ResponseData) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFunction207ResponseData) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateFunction207ResponseData) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateFunction207ResponseData) SetName(v string) {
	o.Name = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *CreateFunction207ResponseData) GetEvents() []CreateFunction207ResponseDataEventsInner {
	if o == nil || isNil(o.Events) {
		var ret []CreateFunction207ResponseDataEventsInner
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFunction207ResponseData) GetEventsOk() ([]CreateFunction207ResponseDataEventsInner, bool) {
	if o == nil || isNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *CreateFunction207ResponseData) HasEvents() bool {
	if o != nil && !isNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []CreateFunction207ResponseDataEventsInner and assigns it to the Events field.
func (o *CreateFunction207ResponseData) SetEvents(v []CreateFunction207ResponseDataEventsInner) {
	o.Events = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreateFunction207ResponseData) GetMetadata() CreateFunction207ResponseDataMetadata {
	if o == nil || isNil(o.Metadata) {
		var ret CreateFunction207ResponseDataMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFunction207ResponseData) GetMetadataOk() (*CreateFunction207ResponseDataMetadata, bool) {
	if o == nil || isNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateFunction207ResponseData) HasMetadata() bool {
	if o != nil && !isNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given CreateFunction207ResponseDataMetadata and assigns it to the Metadata field.
func (o *CreateFunction207ResponseData) SetMetadata(v CreateFunction207ResponseDataMetadata) {
	o.Metadata = &v
}

func (o CreateFunction207ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFunction207ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !isNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableCreateFunction207ResponseData struct {
	value *CreateFunction207ResponseData
	isSet bool
}

func (v NullableCreateFunction207ResponseData) Get() *CreateFunction207ResponseData {
	return v.value
}

func (v *NullableCreateFunction207ResponseData) Set(val *CreateFunction207ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFunction207ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFunction207ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFunction207ResponseData(val *CreateFunction207ResponseData) *NullableCreateFunction207ResponseData {
	return &NullableCreateFunction207ResponseData{value: val, isSet: true}
}

func (v NullableCreateFunction207ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFunction207ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


