/*
Funless Platfom API

The API for the Funless Platform

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// FunctionDeletion struct for FunctionDeletion
type FunctionDeletion struct {
	Name *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// NewFunctionDeletion instantiates a new FunctionDeletion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunctionDeletion() *FunctionDeletion {
	this := FunctionDeletion{}
	return &this
}

// NewFunctionDeletionWithDefaults instantiates a new FunctionDeletion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunctionDeletionWithDefaults() *FunctionDeletion {
	this := FunctionDeletion{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FunctionDeletion) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionDeletion) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FunctionDeletion) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FunctionDeletion) SetName(v string) {
	o.Name = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *FunctionDeletion) GetNamespace() string {
	if o == nil || isNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionDeletion) GetNamespaceOk() (*string, bool) {
	if o == nil || isNil(o.Namespace) {
    return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *FunctionDeletion) HasNamespace() bool {
	if o != nil && !isNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *FunctionDeletion) SetNamespace(v string) {
	o.Namespace = &v
}

func (o FunctionDeletion) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	return json.Marshal(toSerialize)
}

type NullableFunctionDeletion struct {
	value *FunctionDeletion
	isSet bool
}

func (v NullableFunctionDeletion) Get() *FunctionDeletion {
	return v.value
}

func (v *NullableFunctionDeletion) Set(val *FunctionDeletion) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctionDeletion) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctionDeletion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctionDeletion(val *FunctionDeletion) *NullableFunctionDeletion {
	return &NullableFunctionDeletion{value: val, isSet: true}
}

func (v NullableFunctionDeletion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctionDeletion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


