/*
Funless Platfom API

The API for the Funless Platform

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FunctionDeletion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FunctionDeletion{}

// FunctionDeletion struct for FunctionDeletion
type FunctionDeletion struct {
	Name *string `json:"name,omitempty"`
	Module *string `json:"module,omitempty"`
}

// NewFunctionDeletion instantiates a new FunctionDeletion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunctionDeletion() *FunctionDeletion {
	this := FunctionDeletion{}
	return &this
}

// NewFunctionDeletionWithDefaults instantiates a new FunctionDeletion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunctionDeletionWithDefaults() *FunctionDeletion {
	this := FunctionDeletion{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FunctionDeletion) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionDeletion) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FunctionDeletion) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FunctionDeletion) SetName(v string) {
	o.Name = &v
}

// GetModule returns the Module field value if set, zero value otherwise.
func (o *FunctionDeletion) GetModule() string {
	if o == nil || isNil(o.Module) {
		var ret string
		return ret
	}
	return *o.Module
}

// GetModuleOk returns a tuple with the Module field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionDeletion) GetModuleOk() (*string, bool) {
	if o == nil || isNil(o.Module) {
		return nil, false
	}
	return o.Module, true
}

// HasModule returns a boolean if a field has been set.
func (o *FunctionDeletion) HasModule() bool {
	if o != nil && !isNil(o.Module) {
		return true
	}

	return false
}

// SetModule gets a reference to the given string and assigns it to the Module field.
func (o *FunctionDeletion) SetModule(v string) {
	o.Module = &v
}

func (o FunctionDeletion) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FunctionDeletion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Module) {
		toSerialize["module"] = o.Module
	}
	return toSerialize, nil
}

type NullableFunctionDeletion struct {
	value *FunctionDeletion
	isSet bool
}

func (v NullableFunctionDeletion) Get() *FunctionDeletion {
	return v.value
}

func (v *NullableFunctionDeletion) Set(val *FunctionDeletion) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctionDeletion) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctionDeletion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctionDeletion(val *FunctionDeletion) *NullableFunctionDeletion {
	return &NullableFunctionDeletion{value: val, isSet: true}
}

func (v NullableFunctionDeletion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctionDeletion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


