/*
 * Funless Platfom API
 *
 * The API for the Funless Platform
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FunctionCreation struct {
	Name string `json:"name,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	Code string `json:"code,omitempty"`
	Image string `json:"image,omitempty"`
}
