/*
 * FunLess Platfom API
 *
 * The API for the FunLess Platform
 *
 * API version: 0.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1fnmoduleNameEvents struct {
	// Type of the event
	Type_ string `json:"type,omitempty"`
	// Additional parameters of the event
	Params *interface{} `json:"params,omitempty"`
}
