/*
 * Funless Platfom API
 *
 * The API for the Funless Platform
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FunctionInvocation struct {
	Namespace string `json:"namespace,omitempty"`
	Function string `json:"function,omitempty"`
	Args *interface{} `json:"args,omitempty"`
}
