/*
FunLess Platfom API

The API for the FunLess Platform

API version: 0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InvokeFunctionRequest struct for InvokeFunctionRequest
type InvokeFunctionRequest struct {
	Args map[string]interface{} `json:"args,omitempty"`
}

// NewInvokeFunctionRequest instantiates a new InvokeFunctionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvokeFunctionRequest() *InvokeFunctionRequest {
	this := InvokeFunctionRequest{}
	return &this
}

// NewInvokeFunctionRequestWithDefaults instantiates a new InvokeFunctionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvokeFunctionRequestWithDefaults() *InvokeFunctionRequest {
	this := InvokeFunctionRequest{}
	return &this
}

// GetArgs returns the Args field value if set, zero value otherwise.
func (o *InvokeFunctionRequest) GetArgs() map[string]interface{} {
	if o == nil || isNil(o.Args) {
		var ret map[string]interface{}
		return ret
	}
	return o.Args
}

// GetArgsOk returns a tuple with the Args field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvokeFunctionRequest) GetArgsOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.Args) {
    return map[string]interface{}{}, false
	}
	return o.Args, true
}

// HasArgs returns a boolean if a field has been set.
func (o *InvokeFunctionRequest) HasArgs() bool {
	if o != nil && !isNil(o.Args) {
		return true
	}

	return false
}

// SetArgs gets a reference to the given map[string]interface{} and assigns it to the Args field.
func (o *InvokeFunctionRequest) SetArgs(v map[string]interface{}) {
	o.Args = v
}

func (o InvokeFunctionRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Args) {
		toSerialize["args"] = o.Args
	}
	return json.Marshal(toSerialize)
}

type NullableInvokeFunctionRequest struct {
	value *InvokeFunctionRequest
	isSet bool
}

func (v NullableInvokeFunctionRequest) Get() *InvokeFunctionRequest {
	return v.value
}

func (v *NullableInvokeFunctionRequest) Set(val *InvokeFunctionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInvokeFunctionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInvokeFunctionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvokeFunctionRequest(val *InvokeFunctionRequest) *NullableInvokeFunctionRequest {
	return &NullableInvokeFunctionRequest{value: val, isSet: true}
}

func (v NullableInvokeFunctionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvokeFunctionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


