/*
FunLess Platfom API

The API for the FunLess Platform

API version: 0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModuleNameModule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModuleNameModule{}

// ModuleNameModule struct for ModuleNameModule
type ModuleNameModule struct {
	Name *string `json:"name,omitempty"`
}

// NewModuleNameModule instantiates a new ModuleNameModule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModuleNameModule() *ModuleNameModule {
	this := ModuleNameModule{}
	return &this
}

// NewModuleNameModuleWithDefaults instantiates a new ModuleNameModule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModuleNameModuleWithDefaults() *ModuleNameModule {
	this := ModuleNameModule{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModuleNameModule) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModuleNameModule) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModuleNameModule) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModuleNameModule) SetName(v string) {
	o.Name = &v
}

func (o ModuleNameModule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModuleNameModule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableModuleNameModule struct {
	value *ModuleNameModule
	isSet bool
}

func (v NullableModuleNameModule) Get() *ModuleNameModule {
	return v.value
}

func (v *NullableModuleNameModule) Set(val *ModuleNameModule) {
	v.value = val
	v.isSet = true
}

func (v NullableModuleNameModule) IsSet() bool {
	return v.isSet
}

func (v *NullableModuleNameModule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModuleNameModule(val *ModuleNameModule) *NullableModuleNameModule {
	return &NullableModuleNameModule{value: val, isSet: true}
}

func (v NullableModuleNameModule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModuleNameModule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


