/*
FunLess Platfom API

The API for the FunLess Platform

API version: 0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ShowModuleByName200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShowModuleByName200Response{}

// ShowModuleByName200Response struct for ShowModuleByName200Response
type ShowModuleByName200Response struct {
	Data *ShowModuleByName200ResponseData `json:"data,omitempty"`
}

// NewShowModuleByName200Response instantiates a new ShowModuleByName200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShowModuleByName200Response() *ShowModuleByName200Response {
	this := ShowModuleByName200Response{}
	return &this
}

// NewShowModuleByName200ResponseWithDefaults instantiates a new ShowModuleByName200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShowModuleByName200ResponseWithDefaults() *ShowModuleByName200Response {
	this := ShowModuleByName200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ShowModuleByName200Response) GetData() ShowModuleByName200ResponseData {
	if o == nil || isNil(o.Data) {
		var ret ShowModuleByName200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShowModuleByName200Response) GetDataOk() (*ShowModuleByName200ResponseData, bool) {
	if o == nil || isNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ShowModuleByName200Response) HasData() bool {
	if o != nil && !isNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ShowModuleByName200ResponseData and assigns it to the Data field.
func (o *ShowModuleByName200Response) SetData(v ShowModuleByName200ResponseData) {
	o.Data = &v
}

func (o ShowModuleByName200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShowModuleByName200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableShowModuleByName200Response struct {
	value *ShowModuleByName200Response
	isSet bool
}

func (v NullableShowModuleByName200Response) Get() *ShowModuleByName200Response {
	return v.value
}

func (v *NullableShowModuleByName200Response) Set(val *ShowModuleByName200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableShowModuleByName200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableShowModuleByName200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShowModuleByName200Response(val *ShowModuleByName200Response) *NullableShowModuleByName200Response {
	return &NullableShowModuleByName200Response{value: val, isSet: true}
}

func (v NullableShowModuleByName200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShowModuleByName200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


