/*
 * Funless Platfom API
 *
 * The API for the Funless Platform
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FunctionInvocationSuccess struct {
	// The function invocation result
	Result *interface{} `json:"result,omitempty"`
}
