/*
Funless Platfom API

The API for the Funless Platform

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// FunctionInvocationSuccess struct for FunctionInvocationSuccess
type FunctionInvocationSuccess struct {
	// The function invocation result
	Result map[string]interface{} `json:"result,omitempty"`
}

// NewFunctionInvocationSuccess instantiates a new FunctionInvocationSuccess object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunctionInvocationSuccess() *FunctionInvocationSuccess {
	this := FunctionInvocationSuccess{}
	return &this
}

// NewFunctionInvocationSuccessWithDefaults instantiates a new FunctionInvocationSuccess object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunctionInvocationSuccessWithDefaults() *FunctionInvocationSuccess {
	this := FunctionInvocationSuccess{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *FunctionInvocationSuccess) GetResult() map[string]interface{} {
	if o == nil || o.Result == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionInvocationSuccess) GetResultOk() (map[string]interface{}, bool) {
	if o == nil || o.Result == nil {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *FunctionInvocationSuccess) HasResult() bool {
	if o != nil && o.Result != nil {
		return true
	}

	return false
}

// SetResult gets a reference to the given map[string]interface{} and assigns it to the Result field.
func (o *FunctionInvocationSuccess) SetResult(v map[string]interface{}) {
	o.Result = v
}

func (o FunctionInvocationSuccess) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	return json.Marshal(toSerialize)
}

type NullableFunctionInvocationSuccess struct {
	value *FunctionInvocationSuccess
	isSet bool
}

func (v NullableFunctionInvocationSuccess) Get() *FunctionInvocationSuccess {
	return v.value
}

func (v *NullableFunctionInvocationSuccess) Set(val *FunctionInvocationSuccess) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctionInvocationSuccess) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctionInvocationSuccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctionInvocationSuccess(val *FunctionInvocationSuccess) *NullableFunctionInvocationSuccess {
	return &NullableFunctionInvocationSuccess{value: val, isSet: true}
}

func (v NullableFunctionInvocationSuccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctionInvocationSuccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


