/*
FunLess Platfom API

The API for the FunLess Platform

API version: 0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateFunction207ResponseDataMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFunction207ResponseDataMetadata{}

// CreateFunction207ResponseDataMetadata struct for CreateFunction207ResponseDataMetadata
type CreateFunction207ResponseDataMetadata struct {
	// The amount of events that was successfully connected
	Successful *int32 `json:"successful,omitempty"`
	// The amount of events that wasn't successfully connected
	Failed *int32 `json:"failed,omitempty"`
	// The total amount of events that was passed
	Total *int32 `json:"total,omitempty"`
}

// NewCreateFunction207ResponseDataMetadata instantiates a new CreateFunction207ResponseDataMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFunction207ResponseDataMetadata() *CreateFunction207ResponseDataMetadata {
	this := CreateFunction207ResponseDataMetadata{}
	return &this
}

// NewCreateFunction207ResponseDataMetadataWithDefaults instantiates a new CreateFunction207ResponseDataMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFunction207ResponseDataMetadataWithDefaults() *CreateFunction207ResponseDataMetadata {
	this := CreateFunction207ResponseDataMetadata{}
	return &this
}

// GetSuccessful returns the Successful field value if set, zero value otherwise.
func (o *CreateFunction207ResponseDataMetadata) GetSuccessful() int32 {
	if o == nil || isNil(o.Successful) {
		var ret int32
		return ret
	}
	return *o.Successful
}

// GetSuccessfulOk returns a tuple with the Successful field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFunction207ResponseDataMetadata) GetSuccessfulOk() (*int32, bool) {
	if o == nil || isNil(o.Successful) {
		return nil, false
	}
	return o.Successful, true
}

// HasSuccessful returns a boolean if a field has been set.
func (o *CreateFunction207ResponseDataMetadata) HasSuccessful() bool {
	if o != nil && !isNil(o.Successful) {
		return true
	}

	return false
}

// SetSuccessful gets a reference to the given int32 and assigns it to the Successful field.
func (o *CreateFunction207ResponseDataMetadata) SetSuccessful(v int32) {
	o.Successful = &v
}

// GetFailed returns the Failed field value if set, zero value otherwise.
func (o *CreateFunction207ResponseDataMetadata) GetFailed() int32 {
	if o == nil || isNil(o.Failed) {
		var ret int32
		return ret
	}
	return *o.Failed
}

// GetFailedOk returns a tuple with the Failed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFunction207ResponseDataMetadata) GetFailedOk() (*int32, bool) {
	if o == nil || isNil(o.Failed) {
		return nil, false
	}
	return o.Failed, true
}

// HasFailed returns a boolean if a field has been set.
func (o *CreateFunction207ResponseDataMetadata) HasFailed() bool {
	if o != nil && !isNil(o.Failed) {
		return true
	}

	return false
}

// SetFailed gets a reference to the given int32 and assigns it to the Failed field.
func (o *CreateFunction207ResponseDataMetadata) SetFailed(v int32) {
	o.Failed = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *CreateFunction207ResponseDataMetadata) GetTotal() int32 {
	if o == nil || isNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFunction207ResponseDataMetadata) GetTotalOk() (*int32, bool) {
	if o == nil || isNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *CreateFunction207ResponseDataMetadata) HasTotal() bool {
	if o != nil && !isNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *CreateFunction207ResponseDataMetadata) SetTotal(v int32) {
	o.Total = &v
}

func (o CreateFunction207ResponseDataMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFunction207ResponseDataMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Successful) {
		toSerialize["successful"] = o.Successful
	}
	if !isNil(o.Failed) {
		toSerialize["failed"] = o.Failed
	}
	if !isNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableCreateFunction207ResponseDataMetadata struct {
	value *CreateFunction207ResponseDataMetadata
	isSet bool
}

func (v NullableCreateFunction207ResponseDataMetadata) Get() *CreateFunction207ResponseDataMetadata {
	return v.value
}

func (v *NullableCreateFunction207ResponseDataMetadata) Set(val *CreateFunction207ResponseDataMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFunction207ResponseDataMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFunction207ResponseDataMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFunction207ResponseDataMetadata(val *CreateFunction207ResponseDataMetadata) *NullableCreateFunction207ResponseDataMetadata {
	return &NullableCreateFunction207ResponseDataMetadata{value: val, isSet: true}
}

func (v NullableCreateFunction207ResponseDataMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFunction207ResponseDataMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


