/*
FunLess Platfom API

The API for the FunLess Platform

API version: 0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"os"
)

// CreateFunctionRequest struct for CreateFunctionRequest
type CreateFunctionRequest struct {
	Code **os.File `json:"code,omitempty"`
}

// NewCreateFunctionRequest instantiates a new CreateFunctionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFunctionRequest() *CreateFunctionRequest {
	this := CreateFunctionRequest{}
	return &this
}

// NewCreateFunctionRequestWithDefaults instantiates a new CreateFunctionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFunctionRequestWithDefaults() *CreateFunctionRequest {
	this := CreateFunctionRequest{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CreateFunctionRequest) GetCode() *os.File {
	if o == nil || isNil(o.Code) {
		var ret *os.File
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFunctionRequest) GetCodeOk() (**os.File, bool) {
	if o == nil || isNil(o.Code) {
    return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CreateFunctionRequest) HasCode() bool {
	if o != nil && !isNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given *os.File and assigns it to the Code field.
func (o *CreateFunctionRequest) SetCode(v *os.File) {
	o.Code = &v
}

func (o CreateFunctionRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	return json.Marshal(toSerialize)
}

type NullableCreateFunctionRequest struct {
	value *CreateFunctionRequest
	isSet bool
}

func (v NullableCreateFunctionRequest) Get() *CreateFunctionRequest {
	return v.value
}

func (v *NullableCreateFunctionRequest) Set(val *CreateFunctionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFunctionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFunctionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFunctionRequest(val *CreateFunctionRequest) *NullableCreateFunctionRequest {
	return &NullableCreateFunctionRequest{value: val, isSet: true}
}

func (v NullableCreateFunctionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFunctionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


