/*
FunLess Platfom API

The API for the FunLess Platform

API version: 0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InvokeFunction200Response struct for InvokeFunction200Response
type InvokeFunction200Response struct {
	Data map[string]interface{} `json:"data,omitempty"`
}

// NewInvokeFunction200Response instantiates a new InvokeFunction200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvokeFunction200Response() *InvokeFunction200Response {
	this := InvokeFunction200Response{}
	return &this
}

// NewInvokeFunction200ResponseWithDefaults instantiates a new InvokeFunction200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvokeFunction200ResponseWithDefaults() *InvokeFunction200Response {
	this := InvokeFunction200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *InvokeFunction200Response) GetData() map[string]interface{} {
	if o == nil || isNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvokeFunction200Response) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.Data) {
    return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *InvokeFunction200Response) HasData() bool {
	if o != nil && !isNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *InvokeFunction200Response) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o InvokeFunction200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableInvokeFunction200Response struct {
	value *InvokeFunction200Response
	isSet bool
}

func (v NullableInvokeFunction200Response) Get() *InvokeFunction200Response {
	return v.value
}

func (v *NullableInvokeFunction200Response) Set(val *InvokeFunction200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableInvokeFunction200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableInvokeFunction200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvokeFunction200Response(val *InvokeFunction200Response) *NullableInvokeFunction200Response {
	return &NullableInvokeFunction200Response{value: val, isSet: true}
}

func (v NullableInvokeFunction200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvokeFunction200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


