/*
Funless Platfom API

The API for the Funless Platform

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// FunctionInvocationError struct for FunctionInvocationError
type FunctionInvocationError struct {
	// The error message
	Error *string `json:"error,omitempty"`
}

// NewFunctionInvocationError instantiates a new FunctionInvocationError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunctionInvocationError() *FunctionInvocationError {
	this := FunctionInvocationError{}
	return &this
}

// NewFunctionInvocationErrorWithDefaults instantiates a new FunctionInvocationError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunctionInvocationErrorWithDefaults() *FunctionInvocationError {
	this := FunctionInvocationError{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *FunctionInvocationError) GetError() string {
	if o == nil || isNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionInvocationError) GetErrorOk() (*string, bool) {
	if o == nil || isNil(o.Error) {
    return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *FunctionInvocationError) HasError() bool {
	if o != nil && !isNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *FunctionInvocationError) SetError(v string) {
	o.Error = &v
}

func (o FunctionInvocationError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableFunctionInvocationError struct {
	value *FunctionInvocationError
	isSet bool
}

func (v NullableFunctionInvocationError) Get() *FunctionInvocationError {
	return v.value
}

func (v *NullableFunctionInvocationError) Set(val *FunctionInvocationError) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctionInvocationError) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctionInvocationError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctionInvocationError(val *FunctionInvocationError) *NullableFunctionInvocationError {
	return &NullableFunctionInvocationError{value: val, isSet: true}
}

func (v NullableFunctionInvocationError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctionInvocationError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


