/*
 * Funless Platfom API
 *
 * The API for the Funless Platform
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The function invocation result
type InlineResponse200 struct {
	Payload *interface{} `json:"payload,omitempty"`
}
