openapi: 3.1.0
info:
  description: The API for the FunLess Platform
  license:
    name: Apache 2.0
  title: FunLess Platfom API
  version: "0.5"
servers:
- description: The dev server for the FunLess API
  url: http://localhost:4000
tags:
- name: modules
- name: functions
paths:
  /v1/fn:
    get:
      description: List all modules
      operationId: list_modules
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/module_names_result'
          description: An array of modules
          headers:
            X-Total-Count:
              description: Total number of modules
              explode: false
              schema: {}
              style: simple
        default:
          $ref: '#/components/responses/unexpected_error'
      summary: List modules
      tags:
      - modules
    post:
      description: Create a new module
      operationId: create_module
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/module_name'
        description: Module to create
        required: true
      responses:
        "201":
          $ref: '#/components/responses/null_response'
        default:
          $ref: '#/components/responses/unexpected_error'
      summary: Create
      tags:
      - modules
  /v1/fn/{module_name}:
    delete:
      description: Delete module
      operationId: delete_module
      parameters:
      - $ref: '#/components/parameters/module_name'
      responses:
        "204":
          $ref: '#/components/responses/null_response'
        default:
          $ref: '#/components/responses/unexpected_error'
      summary: Delete module
      tags:
      - modules
    get:
      description: "Get module data (name, array of functions, number of functions)"
      operationId: show_module_by_name
      parameters:
      - $ref: '#/components/parameters/module_name'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/single_module_result'
          description: Expected response to a valid request
        default:
          $ref: '#/components/responses/unexpected_error'
      summary: Show module info
      tags:
      - modules
    post:
      description: Create a new function in the specified module
      operationId: create_function
      parameters:
      - $ref: '#/components/parameters/module_name'
      requestBody:
        content:
          multipart/form-data:
            encoding:
              code:
                contentType: application/octet-stream
                style: form
            schema:
              $ref: '#/components/schemas/function_create_update'
        description: Object containing the function's name and code
        required: true
      responses:
        "201":
          $ref: '#/components/responses/null_response'
        "207":
          $ref: '#/components/responses/mixed_response_events'
        default:
          $ref: '#/components/responses/unexpected_error'
      summary: Create new function
      tags:
      - functions
    put:
      description: Update module name
      operationId: update_module
      parameters:
      - $ref: '#/components/parameters/module_name'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/module_name'
        description: New module name to use
        required: true
      responses:
        "200":
          $ref: '#/components/responses/null_response'
        default:
          $ref: '#/components/responses/unexpected_error'
      summary: Update module name
      tags:
      - modules
  /v1/fn/{module_name}/{function_name}:
    delete:
      description: Delete single function in module
      operationId: delete_function
      parameters:
      - description: The name of the module
        explode: false
        in: path
        name: module_name
        required: true
        schema: {}
        style: simple
      - description: The name of the function
        explode: false
        in: path
        name: function_name
        required: true
        schema: {}
        style: simple
      responses:
        "200":
          $ref: '#/components/responses/null_response'
        default:
          $ref: '#/components/responses/unexpected_error'
      summary: Delete function
      tags:
      - functions
    get:
      description: "Get function data (name, module name, size of code)"
      operationId: show_function_by_name
      parameters:
      - $ref: '#/components/parameters/module_name'
      - $ref: '#/components/parameters/function_name'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/single_function_result'
          description: Expected response to a valid request
        default:
          $ref: '#/components/responses/unexpected_error'
      summary: Show function info
      tags:
      - functions
    post:
      description: Invoke function
      operationId: invoke_function
      parameters:
      - description: The name of the module
        explode: false
        in: path
        name: module_name
        required: true
        schema: {}
        style: simple
      - description: The name of the function
        explode: false
        in: path
        name: function_name
        required: true
        schema: {}
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/invoke_input'
        description: Function input
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invoke_result'
          description: Expected response to a valid request
        default:
          $ref: '#/components/responses/unexpected_error'
      summary: Invoke function
      tags:
      - functions
    put:
      description: Update function
      operationId: update_function
      parameters:
      - description: The name of the module
        explode: false
        in: path
        name: module_name
        required: true
        schema: {}
        style: simple
      - description: The name of the function
        explode: false
        in: path
        name: function_name
        required: true
        schema: {}
        style: simple
      requestBody:
        content:
          multipart/form-data:
            encoding:
              code:
                contentType: application/octet-stream
                style: form
            schema:
              $ref: '#/components/schemas/function_create_update'
        description: New function code to use
        required: true
      responses:
        "200":
          $ref: '#/components/responses/null_response'
        "207":
          $ref: '#/components/responses/mixed_response_events'
        default:
          $ref: '#/components/responses/unexpected_error'
      summary: Update function
      tags:
      - functions
components:
  parameters:
    module_name:
      description: The name of the module to retrieve
      explode: false
      in: path
      name: module_name
      required: true
      schema: {}
      style: simple
    function_name:
      description: The name of the function
      explode: false
      in: path
      name: function_name
      required: true
      schema: {}
      style: simple
  responses:
    unexpected_error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Unexpected error
    null_response:
      description: Null response
    mixed_response_events:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/mixed_event_results'
      description: Mixed response
  schemas:
    module_name:
      properties:
        module:
          $ref: '#/components/schemas/module_name_module'
    single_module_result:
      example:
        data:
          functions: ""
          name: ""
      properties:
        data:
          $ref: '#/components/schemas/single_module_result_data'
    module_names_result:
      example:
        data: ""
      properties:
        data:
          items:
            properties:
              name: {}
    single_function_result:
      example:
        data:
          name: ""
      properties:
        data:
          $ref: '#/components/schemas/module_name_module'
    invoke_input:
      properties:
        args: {}
    invoke_result:
      example:
        data: ""
      properties:
        data: {}
    function_create_update:
      properties:
        name:
          description: Name of the function
        code:
          description: File with the code of the function
          format: binary
        events:
          description: Events that can trigger the function
          items:
            properties:
              type:
                description: Type of the event
                oneOf:
                - description: Events produced by an MQTT client/broker
              params:
                description: Additional parameters of the event
    mixed_event_results:
      properties:
        data:
          $ref: '#/components/schemas/mixed_event_results_data'
    error:
      properties:
        errors:
          $ref: '#/components/schemas/error_errors'
      required:
      - errors
    module_name_module:
      example:
        name: ""
      properties:
        name: {}
    single_module_result_data:
      example:
        functions: ""
        name: ""
      properties:
        name: {}
        functions:
          items:
            properties:
              name: {}
    mixed_event_results_data_metadata:
      properties:
        successful:
          description: The amount of events that was successfully connected
        failed:
          description: The amount of events that wasn't successfully connected
        total:
          description: The total amount of events that was passed
    mixed_event_results_data:
      properties:
        name:
          description: The name of the function
        events:
          description: "The results of event connection, both successful and failed"
          items:
            properties:
              status:
                description: Whether the corresponding event was connected successfully
                enum:
                - success
                - error
              message:
                description: Additional information on the error
        metadata:
          $ref: '#/components/schemas/mixed_event_results_data_metadata'
    error_errors:
      properties:
        detail: {}
