openapi: 3.0.2
info:
  description: The API for the FunLess Platform
  license:
    name: Apache 2.0
  title: FunLess Platfom API
  version: "0.5"
servers:
- description: The dev server for the FunLess API
  url: http://localhost:4000
tags:
- name: modules
- name: functions
paths:
  /v1/fn:
    get:
      description: List all modules
      operationId: list_modules
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list_modules_200_response'
          description: An array of modules
          headers:
            X-Total-Count:
              description: Total number of modules
              explode: false
              schema:
                type: integer
              style: simple
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unexpected error
      summary: List modules
      tags:
      - modules
    post:
      description: Create a new module
      operationId: create_module
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_module_request'
        description: Module to create
        required: true
      responses:
        "201":
          description: Null response
        default:
          $ref: '#/paths/~1v1~1fn/get/responses/default'
      summary: Create
      tags:
      - modules
  /v1/fn/{module_name}:
    delete:
      description: Delete module
      operationId: delete_module
      parameters: []
      responses:
        "204":
          $ref: '#/paths/~1v1~1fn/post/responses/201'
        default:
          $ref: '#/paths/~1v1~1fn/get/responses/default'
      summary: Delete module
      tags:
      - modules
    get:
      description: "Get module data (name, array of functions, number of functions)"
      operationId: show_module_by_name
      parameters:
      - description: The name of the module to retrieve
        explode: false
        in: path
        name: module_name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/show_module_by_name_200_response'
          description: Expected response to a valid request
        default:
          $ref: '#/paths/~1v1~1fn/get/responses/default'
      summary: Show module info
      tags:
      - modules
    post:
      description: Create a new function in the specified module
      operationId: create_function
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            encoding:
              code:
                contentType: application/octet-stream
                style: form
            schema:
              $ref: '#/components/schemas/create_function_request'
        description: Object containing the function's name and code
        required: true
      responses:
        "201":
          $ref: '#/paths/~1v1~1fn/post/responses/201'
        "207":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mixed_event_results'
          description: Mixed response
        default:
          $ref: '#/paths/~1v1~1fn/get/responses/default'
      summary: Create new function
      tags:
      - functions
    put:
      description: Update module name
      operationId: update_module
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/paths/~1v1~1fn/post/requestBody/content/application~1json/schema'
        description: New module name to use
        required: true
      responses:
        "200":
          $ref: '#/paths/~1v1~1fn/post/responses/201'
        default:
          $ref: '#/paths/~1v1~1fn/get/responses/default'
      summary: Update module name
      tags:
      - modules
  /v1/fn/{module_name}/{function_name}:
    delete:
      description: Delete single function in module
      operationId: delete_function
      parameters:
      - description: The name of the module
        explode: false
        in: path
        name: module_name
        required: true
        schema:
          type: string
        style: simple
      - description: The name of the function
        explode: false
        in: path
        name: function_name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          $ref: '#/paths/~1v1~1fn/post/responses/201'
        default:
          $ref: '#/paths/~1v1~1fn/get/responses/default'
      summary: Delete function
      tags:
      - functions
    get:
      description: "Get function data (name, module name, size of code)"
      operationId: show_function_by_name
      parameters:
      - description: The name of the function
        explode: false
        in: path
        name: function_name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/show_function_by_name_200_response'
          description: Expected response to a valid request
        default:
          $ref: '#/paths/~1v1~1fn/get/responses/default'
      summary: Show function info
      tags:
      - functions
    post:
      description: Invoke function
      operationId: invoke_function
      parameters:
      - description: The name of the module
        explode: false
        in: path
        name: module_name
        required: true
        schema:
          type: string
        style: simple
      - description: The name of the function
        explode: false
        in: path
        name: function_name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/invoke_function_request'
        description: Function input
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invoke_function_200_response'
          description: Expected response to a valid request
        default:
          $ref: '#/paths/~1v1~1fn/get/responses/default'
      summary: Invoke function
      tags:
      - functions
    put:
      description: Update function
      operationId: update_function
      parameters:
      - description: The name of the module
        explode: false
        in: path
        name: module_name
        required: true
        schema:
          type: string
        style: simple
      - description: The name of the function
        explode: false
        in: path
        name: function_name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          multipart/form-data:
            encoding:
              code:
                contentType: application/octet-stream
                style: form
            schema:
              $ref: '#/paths/~1v1~1fn~1%7Bmodule_name%7D/post/requestBody/content/multipart~1form-data/schema'
        description: New function code to use
        required: true
      responses:
        "200":
          $ref: '#/paths/~1v1~1fn/post/responses/201'
        "207":
          $ref: '#/paths/~1v1~1fn~1%7Bmodule_name%7D/post/responses/207'
        default:
          $ref: '#/paths/~1v1~1fn/get/responses/default'
      summary: Update function
      tags:
      - functions
components:
  parameters:
    module_name:
      $ref: '#/paths/~1v1~1fn~1%7Bmodule_name%7D/get/parameters/0'
    function_name:
      $ref: '#/paths/~1v1~1fn~1%7Bmodule_name%7D~1%7Bfunction_name%7D/get/parameters/1'
  responses:
    unexpected_error:
      $ref: '#/paths/~1v1~1fn/get/responses/default'
    null_response:
      $ref: '#/paths/~1v1~1fn/post/responses/201'
    mixed_response_events:
      $ref: '#/paths/~1v1~1fn~1%7Bmodule_name%7D/post/responses/207'
  schemas:
    module_name:
      $ref: '#/paths/~1v1~1fn/post/requestBody/content/application~1json/schema'
    single_module_result:
      $ref: '#/paths/~1v1~1fn~1%7Bmodule_name%7D/get/responses/200/content/application~1json/schema'
    module_names_result:
      $ref: '#/paths/~1v1~1fn/get/responses/200/content/application~1json/schema'
    single_function_result:
      $ref: '#/paths/~1v1~1fn~1%7Bmodule_name%7D~1%7Bfunction_name%7D/get/responses/200/content/application~1json/schema'
    invoke_input:
      $ref: '#/paths/~1v1~1fn~1%7Bmodule_name%7D~1%7Bfunction_name%7D/post/requestBody/content/application~1json/schema'
    invoke_result:
      $ref: '#/paths/~1v1~1fn~1%7Bmodule_name%7D~1%7Bfunction_name%7D/post/responses/200/content/application~1json/schema'
    function_create_update:
      $ref: '#/paths/~1v1~1fn~1%7Bmodule_name%7D/post/requestBody/content/multipart~1form-data/schema'
    connected_event:
      properties:
        type:
          description: Type of the event
          enum:
          - mqtt
          type: string
        params:
          description: Additional parameters of the event
          type: object
      type: object
    mixed_event_results:
      properties:
        data:
          $ref: '#/components/schemas/mixed_event_results_data'
      type: object
    error:
      properties:
        errors:
          $ref: '#/components/schemas/error_errors'
      required:
      - errors
      type: object
    list_modules_200_response:
      example:
        data:
        - data
        - data
      properties:
        data:
          items:
            type: string
          type: array
      type: object
    create_module_request:
      example:
        name: name
      properties:
        name:
          type: string
      type: object
    show_module_by_name_200_response_data:
      example:
        functions:
        - functions
        - functions
        name: name
      properties:
        name:
          type: string
        functions:
          items:
            type: string
          type: array
      type: object
    show_module_by_name_200_response:
      example:
        data:
          functions:
          - functions
          - functions
          name: name
      properties:
        data:
          $ref: '#/components/schemas/show_module_by_name_200_response_data'
      type: object
    create_function_request:
      properties:
        name:
          description: Name of the function
          type: string
        code:
          description: File with the code of the function
          format: binary
          type: string
        events:
          description: Events that can trigger the function
          items:
            $ref: '#/components/schemas/connected_event'
          type: array
      type: object
    show_function_by_name_200_response:
      example:
        data:
          name: name
      properties:
        data:
          $ref: '#/components/schemas/create_module_request'
      type: object
    invoke_function_request:
      properties:
        args:
          type: object
      type: object
    invoke_function_200_response:
      example:
        data: "{}"
      properties:
        data:
          type: object
      type: object
    mixed_event_results_data_events_inner:
      properties:
        status:
          description: Whether the corresponding event was connected successfully
          enum:
          - success
          - error
          type: string
        message:
          description: Additional information on the error
          type: string
      type: object
    mixed_event_results_data_metadata:
      properties:
        successful:
          description: The amount of events that was successfully connected
          type: integer
        failed:
          description: The amount of events that wasn't successfully connected
          type: integer
        total:
          description: The total amount of events that was passed
          type: integer
      type: object
    mixed_event_results_data:
      properties:
        name:
          description: The name of the function
          type: string
        events:
          description: "The results of event connection, both successful and failed"
          items:
            $ref: '#/components/schemas/mixed_event_results_data_events_inner'
          type: array
        metadata:
          $ref: '#/components/schemas/mixed_event_results_data_metadata'
      type: object
    error_errors:
      properties:
        detail:
          type: string
      type: object
